version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: increase
    schedule:
      interval: "daily"
      time: "18:00"
      timezone: "America/New_York"
    groups:
      "typescript-eslint":
        patterns:
          - "@typescript-eslint/*"
          - "typescript-eslint/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "18:00"
      timezone: "America/New_York"
