on:
  deployment:

name: On deployment created

jobs:
  reject-pending-deployments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Reject pending deployments (preserve-latest)
        uses: ./.github/actions/reject-pending-deployments
        with:
          branch: ${{ github.event.deployment.ref }}
          environment: release
          preserve-latest: true
          sha: ${{ github.event.deployment.sha }}
          token: ${{ secrets.CANCEL_PENDING_DEPLOYMENTS_PERSONAL_ACCESS_TOKEN }}
