name: Create release

on:
  workflow_run:
    workflows: [Test branch]
    branches: [main]
    types:
      - completed

jobs:
  release:
    environment: release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    concurrency:
      group: release-on-main
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Create release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
