name: Create release

on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: Run with dry-run flag
        default: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npx semantic-release ${{github.event.inputs.dry-run == 'true' && '--dry-run' || ''}}
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
