name: Create release

on:
  workflow_run:
    workflows: [Test branch]
    branches: [main]
    types:
      - completed

jobs:
  ready:
    runs-on: ubuntu-latest
    steps:
      - name: Ready
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: echo "Ready to release"
      - name: Fail
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: |
          echo "Required workflow was not successful"
          exit 1

  release:
    needs: ready
    environment: release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    concurrency:
      group: release-on-main
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Create release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
